### ISSUE TITLE
NO_DOCUMENT_RECEIVED error

### ISSUE THREAD

**Issue by developeronrent** [docusign/qs-php#2]
After installing this kit, I updated account id, access token and signer name/email in embed signing ceremony file. When the sign button is clicked, it shows the below error:

````
Warning: file_get_contents(/Applications/XAMPP/xamppfiles/htdocs/qs-php/World_Wide_Corp_lorem.pdf): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/qs-php/qs-01-php-embed-signing-ceremony.php on line 49
Caught exception: [400] Error connecting to the API (https://demo.docusign.net/restapi/v2/accounts/8062977/envelopes) DocuSign API error information: object(stdClass)#18 (2) { ["errorCode"]=> string(20) "NO_DOCUMENT_RECEIVED" ["message"]=> string(237) "The document element did not contain the encoded document, or there is a problem with the encoding. Bytes for document corresponding to documentId 1 not found in request. 'documentId=' possibly missing from Content-Disposition header." }
````

There is not enough documentation on how to resolve this issue on git or docusign articles or Stackoverflow.

**Comment by LarryKlugerDS** [comment]
The problem is that when the PHP program is trying to read the file /Applications/XAMPP/xamppfiles/htdocs/qs-php/World_Wide_Corp_lorem.pdf it is unable to read it.

Suggestions:

1. Check that the file is in the location indicated.
2. If it isn't, then copy the file to that location from the demo_documents directory. 

Also, if you look at lines 49 and 27 of the program, you can see that that the path should include `demo_documents/` **Did you change the program?**
